"""empty message

Revision ID: 30ab8d04845b
Revises: d91a9e2ea9e8
Create Date: 2024-10-11 11:56:21.614963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ab8d04845b'
down_revision = 'd91a9e2ea9e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
