"""empty message

Revision ID: d91a9e2ea9e8
Revises: 63e7e763bbb3
Create Date: 2024-10-11 11:27:42.520988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91a9e2ea9e8'
down_revision = '63e7e763bbb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creature_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('api_search', sa.String(length=120), nullable=False))
        batch_op.drop_column('monster_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bestiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monster_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('api_search')
        batch_op.drop_column('creature_name')

    # ### end Alembic commands ###
