"""empty message

Revision ID: e7a91f7b9a39
Revises: ce76e67ecb5b
Create Date: 2024-10-21 14:04:08.872547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a91f7b9a39'
down_revision = 'ce76e67ecb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bestiary', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bestiary')

    # ### end Alembic commands ###
